# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_link', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
    ]
