# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.URLField(),
        ),
    ]
