# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170817_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='main/static/main/logo.png', upload_to='main/static/main/uploads/'),
        ),
    ]
