# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('organizer', models.CharField(max_length=200)),
                ('organizer_link', models.URLField()),
            ],
        ),
    ]
