# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_team_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='main/static/main/logo.png', upload_to='main/static/main/uploads/'),
        ),
    ]
