# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='main/static/main/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='main/static/main/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
    ]
