# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170914_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(default='main/static/main/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
