# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_mentor_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
