# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_team_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meetup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Meetup'),
        ),
    ]
