# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/static/main/img/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(default='/static/main/img/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/main/img/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='/static/main/img/logo.png', max_length=250, upload_to='main/static/main/uploads/'),
        ),
    ]
