# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_meetup_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='description_en',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
