# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170920_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_el',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='teaser_el',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
    ]
