# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170922_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='current_company',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='current_title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(default='mentor@okthess.gr', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise',
            field=models.CharField(default='expertise default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='industry',
            field=models.CharField(default='industry default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='yearsExp',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='industry',
            field=models.CharField(default='industry default', max_length=200),
            preserve_default=False,
        ),
    ]
