# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:43
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170923_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
