# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:38
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170925_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
