# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170926_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_el',
            field=models.CharField(default='default title', max_length=200),
            preserve_default=False,
        ),
    ]
