# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20170926_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='description_el',
            field=models.TextField(default=None, null=True),
        ),
    ]
