# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170926_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='description_en',
        ),
    ]
