# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20170926_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='description',
            new_name='description_en',
        ),
    ]
