# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170926_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='teaser',
            new_name='teaser_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_en',
        ),
    ]
