# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20170926_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', s3direct.fields.S3DirectField()),
            ],
        ),
    ]
