# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_imagemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('what_text_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('how_text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('how_text_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('participate_text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('participate_text_el', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('coworking_text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('coworking_text_el', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
