# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 16:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkthessMeetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('title', models.TextField(blank=True, null=True)),
                ('agenda', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
