# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_resource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
