# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20171020_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applytext',
            old_name='text',
            new_name='content_el',
        ),
        migrations.AddField(
            model_name='applytext',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='content'),
            preserve_default=False,
        ),
    ]
