# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20171020_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytext',
            name='content_el',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applytext',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
