# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20171024_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
