# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20171023_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okthessmeetup',
            name='agenda',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
