# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20171025_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True, default=None, null=True)),
                ('description_el', models.TextField(blank=True, default=None, null=True)),
                ('image', s3direct.fields.S3DirectField()),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='yearsExp',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
