# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20171030_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
