# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_partner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_4',
        ),
        migrations.AddField(
            model_name='application',
            name='answer_idea_1',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_idea_2',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_idea_3',
            field=models.CharField(choices=[('idea', 'Idea'), ('prototype', 'Prototype'), ('users', 'Early users'), ('revenue', 'Early revenue')], default='idea', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_1',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_2',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_3',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_4',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_5',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_6',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_market_7',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_support_1',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_support_2',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_support_3',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_support_4',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_1',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_2',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_3',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_4',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_5',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_6',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='application',
            name='answer_team_7',
            field=models.TextField(default='default'),
        ),
    ]
