# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20171210_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='answer_market_4',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_market_5',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_market_6',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_market_7',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_team_3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_team_4',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_team_5',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_team_6',
        ),
        migrations.RemoveField(
            model_name='application',
            name='answer_team_7',
        ),
    ]
