# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_event_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
