# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_weekendapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendapplication',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendapplication',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekendapplication',
            name='first_name',
            field=models.TextField(default='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekendapplication',
            name='last_name',
            field=models.TextField(default='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekendapplication',
            name='specialization',
            field=models.TextField(default='specialization'),
            preserve_default=False,
        ),
    ]
