# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20180621_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
