# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_application_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendapplication',
            name='date_applied',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
